name: .NET CI with Liquibase

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Setup Liquibase
      run: |
        curl -sSL https://github.com/liquibase/liquibase/releases/download/v4.28.0/liquibase-4.28.0.tar.gz | tar xz
        echo "$(pwd)/liquibase" >> $GITHUB_PATH
    - name: Validate Liquibase changelogs
      run: |
        liquibase --version
        liquibase validate
